// Code generated by manual core bridge. DO NOT EDIT.
package proto

import (
    context "context"
    grpc "google.golang.org/grpc"
)

type EmptyRequest struct{}

type EngineMetrics struct {
    Status         string  `json:"status"`
    Latency        float64 `json:"latency"`
    SystemLoad     float64 `json:"system_load"`
    Temperature    float64 `json:"temperature"`
    VortexRpm      float64 `json:"vortex_rpm"`
    VortexClock    float64 `json:"vortex_clock"`
    ActiveThreads  int32   `json:"active_threads"`
}

type CoreEngineServiceClient interface {
    StreamMetrics(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (CoreEngineService_StreamMetricsClient, error)
}

type coreEngineServiceClient struct {
    cc grpc.ClientConnInterface
}

func NewCoreEngineServiceClient(cc grpc.ClientConnInterface) CoreEngineServiceClient {
    return &coreEngineServiceClient{cc}
}

func (c *coreEngineServiceClient) StreamMetrics(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (CoreEngineService_StreamMetricsClient, error) {
    stream, err := c.cc.NewStream(ctx, &CoreEngineService_ServiceDesc.Streams[0], "/telemetry.CoreEngineService/StreamMetrics", opts...)
    if err != nil {
        return nil, err
    }
    x := &coreEngineServiceStreamMetricsClient{stream}
    if err := x.ClientStream.SendMsg(in); err != nil {
        return nil, err
    }
    if err := x.ClientStream.CloseSend(); err != nil {
        return nil, err
    }
    return x, nil
}

type CoreEngineService_StreamMetricsClient interface {
    Recv() (*EngineMetrics, error)
    grpc.ClientStream
}

type coreEngineServiceStreamMetricsClient struct {
    grpc.ClientStream
}

func (x *coreEngineServiceStreamMetricsClient) Recv() (*EngineMetrics, error) {
    m := new(EngineMetrics)
    if err := x.ClientStream.RecvMsg(m); err != nil {
        return nil, err
    }
    return m, nil
}

var CoreEngineService_ServiceDesc = grpc.ServiceDesc{
    ServiceName: "telemetry.CoreEngineService",
    HandlerType: (*CoreEngineServiceServer)(nil),
    Methods:     []grpc.MethodDesc{},
    Streams: []grpc.StreamDesc{
        {
            StreamName:    "StreamMetrics",
            Handler:       nil,
            ServerStreams: true,
        },
    },
    Metadata: "telemetry.proto",
}

type CoreEngineServiceServer interface {
    StreamMetrics(*EmptyRequest, CoreEngineService_StreamMetricsServer) error
}

type CoreEngineService_StreamMetricsServer interface {
    Send(*EngineMetrics) error
    grpc.ServerStream
}
