name: Madi Gateway CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/gateway

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/set-up-go@v5
      with:
        go-version: '1.22'

    - name: Initialize Go Module (if missing)
      run: |
        if [ ! -f "go.mod" ]; then
          go mod init madi-gateway
        fi

    - name: Build Gateway
      run: go build -v ./cmd/server/main.go

    - name: Run Tests
      run: go test -v ./...
